<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo empty($title)? '': $title?></title>
<?php if(isset($seok)){?>
<meta name="keywords" content="<?php echo $seok?>"/>
<?php }?>
<?php if(isset($seod)){?>
<meta name="description" content="<?php echo $seod?>"/>
<?php }?>
<script type="text/javascript" src="/js/wvke.com.js"></script>
<style type="text/css">
.table_s01 {width:100%}
.table_s01 th{text-align:left}
</style>
</head>
<body>