<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>后台首页</title>
<link href="/css/style.css" type="text/css" rel="stylesheet" />
</head>

<body>

<div class="container">
  <div class="sidebar1">
    <ul class="nav">
      <li><a href="/manage_blog/list" target="main">博客列表</a></li>
      <li><a href="/manage_blog/save" target="main">+ 博客</a></li>
      <li><a href="/manage_comment/list" target="main">评论列表</a></li>
    </ul>
    <p style="height:500px"></p>
  </div>
  <div class="content">
  	<iframe width="760px" height="650px;" scrolling="auto" frameborder="0" name="main" id="main" src="/manage_blog/list"></iframe>
  </div>
 </div>
</body>
</html>
